const RouteName = {
    SPLSH: "Splash",
    LOGIN_SCREEN : "LoginScreen",
    REGISTER_SCREEN : "Register",
    HOME_SCREEN : "HomeScreen",
    TAB_HOME : "HomeTab",
    TAB_EXERCISE : "ExerciseTab",
    TAB_NOTIFICATION : "NotificationTab",
    TAB_PROFILE : "ProfileTab",
    TAB_CONTACT : "TabContactUs",
    EXERCISE_DETAIL : "ExerciseDetail",
    CHANGE_PASSWORD : "ChangePassword",
    EDIT_PROFILE : "EditProfile",
    PAYMENT : "Payment",
    THANK_YOU : "ThankYou",
    VIDEOCALL : "VideoCall",
    AUDIOCALL_SET : "AudioCall",
    REGIATRAION_SUCCESSFULL : "RegistrationSuccessful",    
    THANKS_SCREEN : "ThankYouScreens",    
    REVIEWS_SCREEN : "ReviewsScreen",   
    AUDIOCALL_VIDEOCALL: 'AudioCallandVideocall',
    CONTACT_TAB: 'TabContactUs',
    END_CALL: 'EndCallScreen',
    SAVECARD_SCREEN: 'SaveCardScreen',
    PAYNOW_SCREEN: 'PayNowScreen',
    DRAWERSCREEN_HOME: 'DrawerHomeScreen',
    DRAWER_EXCERSIE: 'DrawerExcersize',
    DRAWER_NOTIFICATION: 'DrawerNotification',
    DOCTORE_LISTINGPAGE: 'DoctoreListingscreen',
    CHART_DOCTORE_SCREEN: 'DrawerChartScreen',
    DRAWER_HELP_SCREEN: 'DrawerHelpScreen',
    DOCTORE_DETAILES_SCREEN: 'DoctoreDetailesScreen',
    DOCTORE_MAP_LOCATIONS: 'Doctoremapscreen',
    DRAWER_NEWS_SCREEN: 'DrawerNewsScreen', 
    DRAWER_NEWS_DETAILES_SCREEN: 'NewsDetailesScreen', 
    CHART_SCREEN_PERSON: 'ChartScreen', 
    LOGIN_PATINT_TAB_SCREEN: 'LoginandPatientTab', 
    OTP_VERYFY_SCREEN: 'OtpVeryfiveScreen', 
    DRAWER_VIDEOCALL: 'DrawerVideocallScreen', 
    DRAWER_LISTING_SCREEN: 'DrawerListingScreenn', 
    TAB_PROFILE_SCREEN: 'TabProfile',
}
export default RouteName;