const images = {
   back_image : require('../images/icon_back.png'),    
   ic_home : require('./icon_home.png'),
   ic_video : require('./icon_video.png'),
   ic_notify : require('./icon_notification.png'),
   ic_profile : require('./icon_profile.png'),
   ic_homeF : require('./icon_home_fill.png'),
   ic_email : require('./ic_email.png'),
   ic_videoF : require('./icon_video_fill.png'),
   ic_notifyF : require('./icon_notification_fill.png'),
   ic_profileF : require('./icon_profile_fill.png'),
   ic_exercise1 : require('./icon_exercise1.png'),
   ic_exercise2 : require('./icon_exercise2.png'),
   ic_exercise3 : require('./icon_exercise3.png'),
   ic_exercise4 : require('./icon_exercise4.png'),
   ic_exercise5 : require('./icon_exercise5.png'),
   ic_exercise6 : require('./icon_exercise6.png'),
   ic_exercise7 : require('./icon_exercise7.png'),
   ic_arrow_up : require('./icon_arrow_up.png'),
   ic_gpay : require('./icon_gpay.png'),
   ic_arrow_down : require('./icon_arroe_down.png'),
   ic_right : require('./icon_right.png'),
   full_bg_img_hospital: require('./hospital_imag.png'),
   full_bg_img_hospital_two: require('./bg_img_two.png'),
   ic_phone : require('./icon_phone.png'),
   ic_location : require('./icon_location.png'),
   ic_man : require('./icon_man.png'),
   ic_calender : require('./icon_calender.png'),
   ic_landmark : require('./icon_landmark.png'),
   ic_point : require('./icon_point.png'),
   ic_smaily : require('./icon_smaily.png'),
   Paypal_imaglogo:require('./paypallogo.png'),
   Excersizeiconset_set_two:require('./Excersizeimagesetteo.png'),
   Crideit_card:require('./creditcardimage.png'),
   speker_on:require('./spekeron.png'),
   speker_off:require('./spekeroff.png'),
   Color_picker_image:require('./colorpicker.png'),
   Doctore_Width__30:require('./notification.png'),
   Doctore_width__60:require('./yogaimage.png'),
   Doctore_width__100:require('./icon_smaily.png'),
   Doctore_width__110:require('./homeslider6.png'),
   Doctore_width__120:require('./homeslider4.png'),
   Doctore_width__130:require('./homeslider2.png'),
   Doctore_width__150:require('./loginlogo.png'),
   Doctore_width__180:require('./spalashlogo.png'),
   Doctore_width__225:require('./homeslider3.png'),
   Doctore_width__320:require('./homeslider1.png'),
   Doctore_width__370:require('./Accountcreated.png'), 
 }
export default images;